import type { Campaign } from './types'

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Homepage Hero Banner',
    status: 'active',
    channel: 'Web',
    conversionRate: 4.8,
    visitors: 128_400,
    startDate: '2026-01-12',
  },
  {
    id: 'camp-002',
    name: 'Cart Abandonment Popup',
    status: 'active',
    channel: 'Web',
    conversionRate: 12.3,
    visitors: 43_200,
    startDate: '2026-02-01',
  },
  {
    id: 'camp-003',
    name: 'New User Welcome Offer',
    status: 'paused',
    channel: 'Email',
    conversionRate: 7.1,
    visitors: 61_000,
    startDate: '2025-11-20',
  },
  {
    id: 'camp-004',
    name: 'Black Friday Countdown',
    status: 'ended',
    channel: 'Web',
    conversionRate: 15.6,
    visitors: 302_800,
    startDate: '2025-11-25',
  },
  {
    id: 'camp-005',
    name: 'Mobile App Upsell Modal',
    status: 'active',
    channel: 'Mobile',
    conversionRate: 3.2,
    visitors: 89_500,
    startDate: '2026-03-05',
  },
  {
    id: 'camp-006',
    name: 'Loyalty Points Reminder',
    status: 'paused',
    channel: 'Email',
    conversionRate: 9.4,
    visitors: 27_600,
    startDate: '2026-01-28',
  },
  {
    id: 'camp-007',
    name: 'Product Recommendation Carousel',
    status: 'active',
    channel: 'Web',
    conversionRate: 6.7,
    visitors: 154_900,
    startDate: '2025-12-15',
  },
  {
    id: 'camp-008',
    name: 'Exit Intent Discount',
    status: 'ended',
    channel: 'Web',
    conversionRate: 11.2,
    visitors: 76_300,
    startDate: '2025-10-02',
  },
  {
    id: 'camp-009',
    name: 'Push Notification Re-engagement',
    status: 'active',
    channel: 'Mobile',
    conversionRate: 5.5,
    visitors: 42_100,
    startDate: '2026-02-18',
  },
  {
    id: 'camp-010',
    name: 'Winter Sale Landing Page',
    status: 'paused',
    channel: 'Web',
    conversionRate: 8.9,
    visitors: 210_700,
    startDate: '2026-01-05',
  },
]
